services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-database}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  rpc:
    image: prod-template-image:latest
    command: ["/app/rpc"]
    ports:
      - "8000:8000"
    environment:
      RUST_LOG: "info,sqlx=off,sea_orm_migration=off"
      DATABASE_URL: postgresql://user:password@postgres:5432/database
      SOCKET: 0.0.0.0:8000
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl --fail http://localhost:8000/_status/live || exit 1",
    #     ]
    #   interval: 2s
    #   timeout: 5s
    #   retries: 5
    depends_on:
      - postgres
    restart: unless-stopped

  worker:
    image: prod-template-image:latest
    command: ["/app/worker"]
    environment:
      RUST_LOG: "info,sqlx=off,sea_orm_migration=off"
      DATABASE_URL: postgresql://user:password@postgres:5432/database
    depends_on:
      - postgres
      - rpc
    restart: unless-stopped

  # DB explorer in web browser
  # http://localhost:7403/?pgsql=postgres&username=user&db=database&ns=public
  # Password: password
  adminer:
    image: adminer
    ports:
      - 7403:8080
    restart: unless-stopped

  # Grafana: http://localhost:3000/
  # User: admin, Password: admin
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./grafana/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  pgdata:
  grafana-data:
  loki-data:
